name: ellipsized_text
description: âœï¸ One line ellipsized text with the ability to adjust the position of the ellipsis.
version: 2.0.0
repository: https://github.com/ivangalkindeveloper/ellipsized_text

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true