name: ellipsized_text
description: âœï¸ One line ellipsized text with the ability to adjust the position of the ellipsis.
version: 1.1.1
repository: https://github.com/ivangalkindeveloper/ellipsized_text
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
