name: ellipsized_text
description: âœï¸ One line ellipsized text with the ability to adjust the position of the ellipsis.
version: 1.2.0
repository: https://github.com/ivangalkindeveloper/ellipsized_text

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true